

const IMAGES = {
  camera: '/camera.png',
  logo: '/Primary_Logo.png',
  vite: '/vite.svg',
  user: '/User.png',
  cart: '/ShoppingCart.png',
  react: '/react.svg',
  dropdown: '/CaretDown.png',
  dropdownRed: '/Dropdown_red.png',
  funnel: '/Funnel.png',
  phone: '/DeviceMobileCamera.png',
  fashion: '/Dress.png',
  home: '/Armchair.png',
  electronics: '/Monitor.png',
  computing: '/Laptop.png',
  grocery: '/Cherries.png',
  automobiles: '/CarSimple.png',
  garden: '/FlowerLotus.png',
  gaming: '/Joystick.png',
  sporting: '/SoccerBall.png',
  baby: '/BabyCarriage.png',
  heart: '/Heart.png',
  black_heart: '/black_heart.png',
  star: '/Star.png',
  users: '/Users.png',
  headset: '/Headset.png',
  question: '/Question.png',
  ranking: '/Ranking.png',
  sealPercent: '/SealPercent.png',
  loginimg: '/login_img.png',
  lock: '/lock.png',
  sms: '/sms.png',
  eye: '/eye.png',
  xCircle: '/XCircle.png',
  services1: '/Services (1).png',
  services2: '/Services (2).png',
  services3: '/Services (3).png',
  services4: '/Services (4).png',
  services5: '/Services (5).png',
  services6: '/Services (6).png',
  services7: '/Services (7).png',
  services8: '/Services (8).png',
  users1: '/Users (1).png',
  avatar_1: '/Avatar_1.png',
  signout: '/SignOut.png',
  ellipseStore: '/Ellipse_store_img.png',
  starFilled: '/StarFilled.png',
  storeImg: '/StoreImg.png',
  kebab: '/kebab.png',
  message: '/message.png',
  phoneIcon: '/phone.png',
  servicesDetail1: '/Services_detail_1.png',
  servicesDetail2: '/Services_detail_2.png',
  servicesDetail3: '/Services_detail_3.png',
  video: '/video.png',
  whatsapp: '/whatsapp.png',
  maincategory: '/maincategory.png',
  sasha: '/sasha.svg',
  mappin: '/MapPin.svg',
  shoppingCart: '/shopping-cart.svg',
  caretRight: '/CaretRight.png',
  adam: '/Adam.png',
  adewale: '/Adewale.png',
  automobile: '/AutoMobile.png',
  beautyandhealth: '/beautyandhealth.png',
  catFashion: '/Cat_Fashion.png',
  computingCat: '/Computing.png',
  electronicCat: '/Electronic.png',
  favour: '/Favour.png',
  foodandgrocery: '/foodandgrocery.png',
  gamingCat: '/Gaming.png',
  gardenCat: '/Garden.png',
  groceryCat: '/Grocery.png',
  homeCat: '/Home.png',
  mobileCat: '/mobile.png',
  phoneTablet: '/Phone_Tablet.png',
  sashaImg: '/Sasha.png',
  scent: '/Scent.png',
  servicesCat: '/services.png',
  sportsCat: '/Sports.png',
  tarra: '/Tarra.png',
  top1: '/top1.png',
  top2: '/top2.png',
  top3: '/top3.png',
  top4: '/top4.png',
  top5: '/top5.png',
  top6: '/top6.png',
  vee: '/Vee.png',
  feedPhone: '/FeedPhone.png',
  download: '/Download.png',
  shop: '/shop.svg',
  followers: '/followers.svg',
  kebab1: '/kebabmenu1.png',
  heart1: '/heart1.png',
  scentVilla: '/ScentVilla.png',
  lovina: '/Lovina.png',
  caremal: '/Caremal.png',
  coverSasha: '/coverSasha.png',
  coverVee: '/coverVee.png',
  coverCaremal: '/coverCaremal.png',
  coverAdam: '/coverAdam.png',
  coverScent: '/coverScent.png',
  coverLovina: '/coverLovina.png',
  star1: '/Star.svg',
  reply: '/ArrowBendDoubleUpLeft.png',
  cartwithprice1: '/ShoppingCartSimple.svg',
  reveal1: '/reveal1.svg',
  reveal2: '/reveal2.svg',
  reveal3: '/reveal3.svg',
  facebook: '/facebook.svg',
  whatsapp1: '/whatsapp.svg',
  twitter: '/twitter.svg',
  instagram: '/instagram.svg',
  verification: '/verification.png',
  Shop: '/shop.png',
  profile: '/profile.png',
  starBlack: '/starBlack.png',
  megaphone: '/Megaphone.png',
  x: '/X.png',
  paperPlaneRight: '/PaperPlaneRight.png',
  whatsappIcon: '/whats_app.png',
  grosry: '/grosry.png',

};
export default IMAGES;
