

const IMAGES = {
  camera: '/camera.png',
  logo: '/Primary_Logo.png',
  vite: '/vite.svg',
  user: '/User.png',
  cart: '/ShoppingCart.png',
  react: '/react.svg',
  dropdown: '/CaretDown.png',
  phone: '/DeviceMobileCamera.png',
  fashion: '/Dress.png',
  home: '/Armchair.png',
  electronics: '/Monitor.png',
  computing: '/Laptop.png',
  grocery: '/Cherries.png',
  automobiles: '/CarSimple.png',
  garden: '/FlowerLotus.png',
  gaming: '/Joystick.png',
  sporting: '/SoccerBall.png',
  baby: '/BabyCarriage.png',
  heart: '/Heart.png',
  star: '/Star.png',
  users: '/Users.png',
  headset: '/Headset.png',
  question: '/Question.png',
  ranking: '/Ranking.png',
  sealPercent: '/SealPercent.png',
  loginimg: '/login_img.png',
  lock: '/lock.png',
  sms: '/sms.png',
  eye: '/eye.png',
  xcircle: '/XCircle.png',
  services1: '/Services (1).png',
  services2: '/Services (2).png',
  services3: '/Services (3).png',
  services4: '/Services (4).png',
  services5: '/Services (5).png',
  services6: '/Services (6).png',
  services7: '/Services (7).png',
  services8: '/Services (8).png',
  users1: '/Users (1).png',
  avatar_1: '/Avatar_1.png',
  signout: '/SignOut.png',
  ellipseStore: '/Ellipse_store_img.png',
  starFilled: '/StarFilled.png',
  storeImg: '/StoreImg.png',
  maincategory: '/maincategory.png',
};
export default IMAGES;
